### ISSUE TITLE
SpreadsheetDocument.Dispose() throws System.ObjectDisposedException

### ISSUE THREAD

**Issue by sszymons** [dotnet/Open-XML-SDK#1702] opened 2024-04-03 11:48 UTC
**Describe the bug**
SpreadsheetDocument.Dispose() throws System.ObjectDisposedException: Cannot access a closed Stream.

**Screenshots**
![image](https://github.com/dotnet/Open-XML-SDK/assets/165906541/eac158d5-f7df-46ed-a2e8-e8c049a67256)

**To Reproduce**

```
         Stream stream = new MemoryStream();
         var spreadsheetDocument = SpreadsheetDocument.Create(stream, SpreadsheetDocumentType.Workbook);
         spreadsheetDocument.Save();
         
         stream.Dispose();
         spreadsheetDocument.Dispose();

```

**Observed behavior**
Exception is thrown.

`System.ObjectDisposedException : Cannot access a closed Stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at System.IO.Compression.ZipArchive.Dispose()
   at System.IO.Packaging.ZipPackage.Dispose(Boolean disposing)
   at System.IO.Packaging.Package.System.IDisposable.Dispose()
   at System.IO.Packaging.Package.Close()
   at DocumentFormat.OpenXml.Features.StreamPackageFeature.Dispose(Boolean disposing)
   at DocumentFormat.OpenXml.Features.StreamPackageFeature.Dispose()
   at DocumentFormat.OpenXml.Packaging.PackageFeatureCollection.DocumentFormat.OpenXml.Features.IContainerDisposableFeature.Dispose()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose(Boolean disposing)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose()`

**Expected behavior**
Should not throw exception, according to:https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065

_A [System.IDisposable.Dispose](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) method should not throw an exception. Dispose is often called as part of the cleanup logic in a finally clause. Therefore, explicitly throwing an exception from Dispose forces the user to add exception handling inside the finally clause._

**Desktop (please complete the following information):**
 - OS: MasOS 13.5 
 - Office version: N/A
 - .NET Target: .NET 6
 - DocumentFormat.OpenXml Version: 3.0.2

**Comment by jrose323** [comment] 2024-04-03 20:14
I wonder if this could be related to an issue I am seeing which started with version 3.0. When Dispose is executed, I run a script right after to delete the file, however, it fails as the file is still in use. It would seem that Dispose is not properly releasing all resources upon execution.

**Comment by m-gallesio** [comment] 2024-05-15 07:11
Have you considered moving from manual `.Dispose()` to [`using` statements](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using)?

**Comment by sszymons** [comment] 2024-05-15 08:40
> Have you considered moving from manual `.Dispose()` to [`using` statements](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using)?

Of course. The original implementation use using statement. The example is just simplified.

**Comment by edwardneal** [comment] 2024-05-28 19:51
This is because of behaviour in ZipArchive. This behaviour needs to change, but by way of explanation: although calling SpreadsheetDocument.Save will persist the relevant parts into the ZipArchive, the ZipArchive won't be persisted into its stream. There's a PR to add ZipArchive.Flush to do this, dotnet/runtime#24149.

ZipArchive won't flush its content into the stream until the ZipArchive instance is disposed of. This happens when the Package is disposed of, which in turn happens when the SpreadsheetDocument is disposed of.

In the sample, you're disposing of the stream, then the SpreadsheetDocument, so when the ZipArchive tries to flush its content into the stream, it throws the ObjectDisposedException you've found. If you dispose of the SpreadsheetDocument before the stream, I think it'll work.

The complete fix would be for ZipArchive to implement Flush, then for ZipPackage to use this so that the Dispose behaviour can be reviewed (at the very least, so it doesn't throw if you Dispose straight after calling SpreadsheetDocument.Save.) This needs to wait for the PR linked above though.

**Comment by sszymons** [comment] 2024-05-29 13:43
> This is because of behaviour in ZipArchive. This behaviour needs to change, but by way of explanation: although calling SpreadsheetDocument.Save will persist the relevant parts into the ZipArchive, the ZipArchive won't be persisted into its stream. There's a PR to add ZipArchive.Flush to do this, [dotnet/runtime#24149](https://github.com/dotnet/runtime/issues/24149).
> 
> ZipArchive won't flush its content into the stream until the ZipArchive instance is disposed of. This happens when the Package is disposed of, which in turn happens when the SpreadsheetDocument is disposed of.
> 
> In the sample, you're disposing of the stream, then the SpreadsheetDocument, so when the ZipArchive tries to flush its content into the stream, it throws the ObjectDisposedException you've found. If you dispose of the SpreadsheetDocument before the stream, I think it'll work.
> 
> The complete fix would be for ZipArchive to implement Flush, then for ZipPackage to use this so that the Dispose behaviour can be reviewed (at the very least, so it doesn't throw if you Dispose straight after calling SpreadsheetDocument.Save.) This needs to wait for the PR linked above though.

I got it. Thank you! We cannot do anything in Open XML SDK implementation. Can this issue stay open for visibility?

**Comment by twsouthwick** [comment] 2024-06-13 22:17
I don't think this is the ziparchive - you have the dispose statements the wrong direction. This is part of why `using` statements are so much better. Try:

```diff
Stream stream = new MemoryStream();
 var spreadsheetDocument = SpreadsheetDocument.Create(stream, SpreadsheetDocumentType.Workbook);
 spreadsheetDocument.Save();
 
- stream.Dispose();
 spreadsheetDocument.Dispose();
+ stream.Dispose();
```

The ziparchive may play into it, but disposing out of order like this is guessing at what the implementation should be doing. Even if "spreadsheetDocument.Save()` flushed everything, the dispose may do additional cleanup and map expect the underlying package/stream to still be available.

**Comment by twsouthwick** [comment] 2024-06-13 22:26
I'm going to close this as it's by design here. Feel free to reopen if this doesn't resolve it.

**Closed by twsouthwick** 2024-06-13 22:26 UTC
