### ISSUE TITLE
Reading large  Excel document with Open XML SAX model

### ISSUE THREAD

**Issue by nkramakrishnan** [dotnet/Open-XML-SDK#1335] opened 2023-02-01 22:42 UTC
We are trying to read a comments and find if the track changes are enabled on a large excel document through SAX model

Describe the solution you'd like
We would like to read/open a large Excel file and find the comments in it

Describe alternatives you've considered
We are able to read comments using Open XML DOM model but leads to higher memory demand approx. 9x than original file size.

Additional context

Sample pseudo code below

```csharp
using (var reader = OpenXmlReader.Create(spreadSheetDocument.WorkbookPart))
{
    while(reader.Read())
    {
        Console.WriteLine(reader.ElementType);
        // Can't the below if be better readable?
        if (reader?.ElementType == typeof(CommentRangeStart))
        {
            // Chance that this is a comment.
            //CommentRangeStart element = reader.LoadCurrentElement() as CommentRangeStart;
            //Console.WriteLine($"Comment text {reader.GetText()}, InnerText:{element.InnerText}");
            result = true;
        }
        else if(reader.ElementType == typeof(Deleted)
              || reader.ElementType == typeof(Inserted)
              || reader.ElementType == typeof(InsertedRun)
              || reader.ElementType == typeof(InsertedMathControl)
              || reader.ElementType == typeof(ParagraphPropertiesChange)
              )
        {
            result = true;
        }
    }
}
```

*@twsouthwick edited for format*

**Comment by twsouthwick** [comment] 2023-02-03 17:26
Hi @nkramakrishnan we've similar issues raised in the past. I'm happy to take contributions around this area, but I'd need to see what the design would look like first.

**Comment by twsouthwick** [comment] 2023-02-03 17:27
I believe this is a dupe of #1193 . Please reopen if you think it's different, but that has a proposal for what needs to happen in the SDK so I'll close this in favor of that one.

**Closed by twsouthwick** 2023-02-03 17:27 UTC
Labels: request: feature, api-design-needed
