### ISSUE TITLE
Expose IPackage instead of Package.

### ISSUE THREAD

**Issue by sergey-tihon** [dotnet/Open-XML-SDK#1412] opened 2023-04-19 07:01 UTC
**Describe the bug**
Obsolete `Package` property break [Clippit](https://github.com/sergey-tihon/Clippit/pull/63/files) library (ex OpenXmlPowerTools)

**Screenshots**
![image](https://user-images.githubusercontent.com/1197905/232991966-03acf6c0-bd12-43ae-817c-ac454b7ebea1.png)

**To Reproduce**
Here is the branch with updated OpenXML version and all build errors - https://github.com/sergey-tihon/Clippit/pull/63/files

**Observed behavior**
No way to upgrade to `2.20.0`

**Expected behavior**
Exposed `IPackage`, mostly used for `GetParts()` and `GetPart()`

**Comment by twsouthwick** [comment] 2023-04-19 20:02
Duplicate of #1400

**Closed by twsouthwick** 2023-04-19 20:02 UTC

**Comment by RakhiNarayanan** [comment] 2024-07-05 08:20
I am trying to use DocumentFormat::OpenXml::Packaging::IPackage,but it is throwing error while ccompilation.

error C4950: 'DocumentFormat::OpenXml::Packaging::IPackage': marked as obsolete
nvsdocument.cpp(399): note: Message: 'This is an experimental APIs and is subject to change'

Intially I was using System.IO.Packaging.Package` for openxmlsdk 2.19,whereas it is not supported in 3.0.2,how to resolve this error.
