### ISSUE TITLE
Get Current Page n

### ISSUE THREAD

**Issue by adriana-185** [dotnet/Open-XML-SDK#1515] opened 2023-08-28 12:17 UTC
I have a part of a code that opens a docx document and edits it, it adds several things and one of those is the page number you're currently in, so it should look like "Pag: 1/5". Until last week it worked just fine, but today I noticed that it no longer displays the current page number but displays in its' place "{PAGE}", ending up with "Pag:{PAGE}/5". I'm using this code on a project and both the testing code and the server code have this problem (and I haven't updated the server code in more than a month.

The following code is how it gets the current page number, which worked before:
` run.AppendChild(new SimpleField() { Instruction = "PAGE" });`

The full part that the code is in:
```
pageCount = int.Parse(doc.ExtendedFilePropertiesPart.Properties.Pages.Text);
paragraph = td32.AppendChild(new Paragraph(
        new ParagraphProperties(
            new Justification() { Val = JustificationValues.Left },
            new Bold() { Val = OnOffValue.FromBoolean(true) })));
run = paragraph.AppendChild(new Run());
run.RunProperties = new DocumentFormat.OpenXml.Wordprocessing.RunProperties();
fontSize = new DocumentFormat.OpenXml.Wordprocessing.FontSize() { Val = "22" };
run.RunProperties.Append(fontSize);
runFonts = new RunFonts() { Ascii = "Arial", HighAnsi = "Arial" };
run.RunProperties.Append(runFonts);
bold = new Bold() { Val = false };
run.RunProperties.Append(bold);
italic = new Italic() { Val = false };
run.RunProperties.Append(italic);
run.AppendChild(new Text("Pág: "));
run.AppendChild(new SimpleField() { Instruction = "PAGE" });
run.AppendChild(new Text("/" + pageCount));
```

**Comment by tomjebo** [comment] 2023-08-29 20:40
Hi @adriana-185, 

The {PAGE} field that your code inserts is working as expected. The problem is that it is not automatically updated. If you right click on the field location in Word's UI, you can select !Update Field and it will show the correct page number. The reason for this is that PAGE or other pagination related fields are calculated at print time by default. Please refer to this article to see the explanation: 
[Some fields are updated while other fields are not](https://support.microsoft.com/en-us/topic/some-fields-are-updated-while-other-fields-are-not-eb3ad53a-328b-a3b4-91c6-28a84001855f)

**Comment by tomjebo** [comment] 2023-08-29 22:59
@adriana-185, 

I can add a little more here. What I think you're missing is a w:t or text child element for the fldSimple element or SimpleField object.  If you do something like this: 

```csharp
    run.RunProperties.Append(italic);
    run.AppendChild(new Text("Pág: "));
    run.AppendChild(new SimpleField(new Text("3")) { Instruction = "PAGE" });
    run.AppendChild(new Text("/" + pageCount));
```

Then at least you will see the placeholder number, in this case "3" next to the "/5" or whatever the page count ends up being. However, it still stands that this will not update automatically. You will have to tell Word to update the field to reflect the current page and not just the placeholder value you added in code. 

Hopefully that will help you.

**Comment by tomjebo** [comment] 2023-10-19 22:58
@adriana-185 are you ok to close this?

**Closed** 2023-10-23 17:27 UTC
Labels: by design
