### ISSUE TITLE
Reading comments from PowerPoint using Open XML SDK SAX Model

### ISSUE THREAD

**Issue by RajneeshVerma** [dotnet/Open-XML-SDK#1334] opened 2023-02-01 22:22 UTC
**Is your feature request related to a problem? Please describe.**
We are trying to read comments of large files and if we use DOM based reading then memory utilization is very high, hence looking a solution with SAX model.

**Describe the solution you'd like**
I would like to read/open large PowerPoint file and find comments in it

**Describe alternatives you've considered**
We are able to read comments using DOM model but its utilizing higher memory approx. 9x than original file size.

**Additional context**
Sample pseudo code as below
```csharp
using (var presentationDocument = PresentationDocument.Open(stream, false))
{
    using (var reader = OpenXmlReader.Create(presentationDocument?.PresentationPart))
    {
        while (reader.Read())
        {
            Console.WriteLine(reader.ElementType);
            //Looking if any comments are present in any of the slides, then read them.
        }                   
    }
}
```

*edited for format*

**Comment by twsouthwick** [comment] 2023-02-03 17:27
Wow - 2 similar issues in a day :) I believe this is a dupe of #1193 . Please reopen if you think it's different, but that has a proposal for what needs to happen in the SDK so I'll close this in favor of that one.

**Closed by twsouthwick** 2023-02-03 17:27 UTC
